fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake -r -i --remove-all-unused-imports --remove-unused-variables
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.30.0
      hooks:
        -   id: pyupgrade
  -   repo: https://github.com/returntocorp/semgrep
      rev: 'v0.77.0'
      hooks:
        - id: semgrep
          name: Semgrep Python / Bandit
          types: [ python ]
          args: [ '--config', 'p/python', '--config', 'p/bandit', '--error' ]
