fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '^docs/'
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake -r -i --remove-all-unused-imports --remove-unused-variables
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py37-plus
        language: system
        types: [ python ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
      - id: pycco
        name: pycco
        entry: pycco -p
        language: system
        types: [ python ]
      - id: readme-docs
        name: Readme documentation
        description: Using [python help], inserts into README.md.
        entry: python3 readme_docs.py
        language: system
        pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
